config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
  validates :name, :address, :description, :price_per_night, :number_of_guests, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    if @flat.save
      redirect_to flats_path
    else
      render :new
    end
  end

  def edit
  end

  def update
  end

  def destroy
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description, :price_per_night, :number_of_guests, :img_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<div class="container w-50 mt-5" style="background-color: #F8F9FA">

  <h1 class="pt-3">New Flat</h1>

  <%= simple_form_for flat do |f| %>
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :description %>
    <%= f.input :img_url, label: "Image Path" %>
    <%= f.input :price_per_night %>
    <%= f.input :number_of_guests %>
    <%= f.submit "Create Flat", class: "btn btn-primary" %>
    <br>
    <%= link_to "Cancel", flats_path, class: "btn btn-outline-primary py-0 mt-2" %>
  <% end %>
</div>

app/views/flats/_navbar.html.erb
<nav class="navbar navbar-light bg-light d-flex justify-content-between">
  <div>
     <%= link_to "Available Flats", flats_path, class: 'navbar-brand' %>
  </div>
  <div class="flex">
    <form class="form-inline">
      <input type="search" name="query" class="form-control" placeholder="Search">
      <button class="btn btn-outline-info ml-2" type="submit">Search</button>
       <%= link_to "Add Flat", new_flat_path, class: 'navbar-brand btn btn-outline-secondary ml-2'  %>
    </form>

  </div>
</nav>

app/views/flats/edit.html.erb
edit.html.erb

app/views/flats/index.html.erb
<%= render 'navbar' %>
<div class="container">
  <h1 class="mt-3">All our Flats (<%= @flats.count %>)</h1>
  <div class="flats d-flex flex-wrap justify-content-center">
    <% @flats.each do |flat| %>
      <div class="card col-3 p-0 m-3">
        <div class="img-container">
          <img src=<%= flat.img_url %> class="card-img-top card-my-img" alt="#">
        </div>
        <div class="card-body">
          <h5 class="card-title"><%= flat.name %></h5>
          <p class="card-text"><%= flat.address %></p>
          <p class="mb-0"><i class="fas fa-user-friends"></i> <%= flat.number_of_guests %>  <i class="fas fa-euro-sign ml-3"></i> <%= flat.price_per_night %></p>
        </div>
        <div class="card-body py-2 border-top d-flex align-items-center">
          <%= link_to "More info", flat_path(flat.id) %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
show.html.erb

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>